"""Script export for section documents (ADR 0080 B4).

``SectionDocument.export_script()`` renders the document as a
**readable, runnable** apeGmsh Python script — the same calls a user
would hand-write. Export is one-way by design (round-trip editing is
the JSON document's job); determinism and execution-equivalence are
the contract, both tested.

- Continuum lane: session → builders / polygon geometry → booleans →
  mesh → ``SectionProperties`` bound to the name ``sec``. Executing
  the script reproduces the document's analyzer numbers exactly (same
  call order → deterministic mesh). The bars overlay and the bridge
  handoff are emitted as a commented epilogue (they need a frame
  model's ``apeSees`` bridge).
- Fiber lane: a ``build_section(ops)`` function — uniaxial materials
  from the document's specs, template expansions inlined as literals
  with provenance comments, returning the registered
  ``ops.section.Fiber``.
"""
from __future__ import annotations

import json
from typing import Any


__all__ = ["render_script"]


def _fmt(value: Any) -> str:
    """Literal formatting: floats via repr (round-trip exact),
    strings via json (stable quoting)."""
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    return repr(value)


def _kwargs(mapping: "dict[str, Any]", keys: "tuple[str, ...]") -> str:
    return ", ".join(f"{k}={_fmt(mapping[k])}" for k in keys)


def render_script(doc: Any) -> str:
    """Render one :class:`~apeGmsh.sections.SectionDocument` to
    script text (the ``export_script`` engine)."""
    if doc.kind == "fiber":
        return _render_fiber(doc)
    return _render_continuum(doc)


# ── continuum lane ───────────────────────────────────────────────────


def _render_continuum(doc: Any) -> str:
    data = doc.to_dict()
    name = data.get("name") or "section"
    sacrificial = {
        op["tool"]
        for op in data["booleans"]
        if op["op"] == "cut" and op.get("remove_tool", True)
    }
    out: list[str] = [
        f'"""Generated by apeGmsh SectionDocument {name!r} '
        f'(section_doc_version {data["section_doc_version"]}).\n'
        f'One-way export: edit the .section.json (or this script), '
        f'not both."""',
        "from apeGmsh import apeGmsh",
        "from apeGmsh.sections import SectionMaterial, SectionProperties",
        "",
        f"g = apeGmsh(model_name={_fmt(name)})",
        "g.begin()",
        "",
    ]
    var_of: dict[str, str] = {}
    faces_of: dict[str, str] = {}
    for i, sh in enumerate(data["shapes"]):
        var = f"s{i}_{_ident(sh['id'])}"
        var_of[sh["id"]] = var
        if sh["shape"] == "polygon":
            # polygon vars hold a raw surface tag (cut/fragment accept
            # it with dim=2); builder vars hold an Instance
            faces_of[sh["id"]] = var
            out += _polygon_code(sh, var, pg=sh["id"] not in sacrificial)
        else:
            faces_of[sh["id"]] = f"{var}.entities[2]"
        if sh["shape"] != "polygon":
            args = [
                f"{k}={_fmt(v)}" for k, v in sh["params"].items()
            ]
            args.append(f"label={_fmt(sh['id'])}")
            if tuple(sh["translate"]) != (0.0, 0.0):
                args.append(
                    f"translate=({_fmt(sh['translate'][0])}, "
                    f"{_fmt(sh['translate'][1])})"
                )
            if sh["rotate"] is not None:
                args.append(f"rotate={_fmt(sh['rotate'])}")
            out.append(
                f"{var} = g.sections.{sh['shape']}({', '.join(args)})"
            )
    out.append("")
    for op in data["booleans"]:
        if op["op"] == "embed":
            a, b = faces_of[op["outer"]], faces_of[op["inner"]]
            out += [
                "# embed: carve then fragment (the composite-partition "
                "primitive)",
                f"g.model.boolean.cut({a}, {b}, "
                f"dim=2, remove_tool=False)",
                f"g.parts.fragment_pair({_fmt(op['outer'])}, "
                f"{_fmt(op['inner'])}, dim=2)",
            ]
        elif op["op"] == "cut":
            a, b = faces_of[op["target"]], faces_of[op["tool"]]
            out.append(
                f"g.model.boolean.cut({a}, {b}, "
                f"dim=2, remove_tool={op.get('remove_tool', True)})"
            )
        else:
            out.append(
                f"g.parts.fragment_pair({_fmt(op['a'])}, "
                f"{_fmt(op['b'])}, dim=2)"
            )
    if sacrificial:
        out.append("g.model.geometry.remove_orphans()")
    out += [
        "",
        f"g.mesh.sizing.set_global_size({_fmt(data['mesh']['lc'])})",
        "g.mesh.generation.generate(dim=2)",
    ]
    if int(data["mesh"].get("order", 2)) > 1:
        out.append("g.mesh.generation.set_order(2)")
    out += [
        "fem = g.mesh.queries.get_fem_data(dim=2)",
        "g.end()",
        "",
    ]
    mats = _continuum_materials(data, sacrificial)
    if mats:
        out.append("materials = {")
        out += mats
        out.append("}")
        mat_arg = "materials=materials, "
    else:
        mat_arg = ""
    out.append(
        f"sec = SectionProperties(fem, {mat_arg}name={_fmt(name)}, "
        f"disconnected={_fmt(data.get('disconnected', 'raise'))})"
    )
    bars = data.get("bars", [])
    if bars:
        out += ["", "# bars overlay (authoring coords) — resolve on a "
                    "bridge via the DOCUMENT:",
                "#   cs = doc.to_section(ops)   # ComputedSection("
                "kind='fiber', fibers=..., bars=...)"]
        for b in bars:
            out.append(f"#   {json.dumps(b)}")
    out += [
        "",
        "# bridge handoff (elastic lowering):",
        "#   girder = ops.section.ComputedSection(analysis=sec)",
        "",
    ]
    return "\n".join(out)


def _ident(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s)


def _polygon_code(sh: "dict[str, Any]", var: str, *, pg: bool) -> list[str]:
    """Polygon authoring with the placement baked into the emitted
    coordinates (same math as the document build)."""
    import math

    dx, dy = sh["translate"]
    theta = (
        math.radians(sh["rotate"]) if sh["rotate"] is not None else None
    )
    pts = []
    for x, y in sh["points"]:
        if theta is not None:
            x, y = (
                x * math.cos(theta) - y * math.sin(theta),
                x * math.sin(theta) + y * math.cos(theta),
            )
        pts.append((x + dx, y + dy))
    lines = [f"# polygon {sh['id']!r} (placement baked into coords)"]
    lines.append(
        f"{var}_pts = ["
        + ", ".join(
            f"g.model.geometry.add_point({_fmt(x)}, {_fmt(y)}, 0.0)"
            for x, y in pts
        )
        + "]"
    )
    lines.append(
        f"{var}_lines = [g.model.geometry.add_line({var}_pts[i], "
        f"{var}_pts[(i + 1) % len({var}_pts)]) "
        f"for i in range(len({var}_pts))]"
    )
    lines.append(
        f"{var}_surf = g.model.geometry.add_plane_surface("
        f"[g.model.geometry.add_curve_loop({var}_lines)])"
    )
    if pg:
        lines.append(
            f"g.physical.add(2, [{var}_surf], name={_fmt(sh['id'])})"
        )
    lines.append(f"{var} = {var}_surf")
    return lines


def _continuum_materials(
    data: "dict[str, Any]", sacrificial: "set[str]",
) -> list[str]:
    table = data["materials"]
    if not table:
        return []
    out = []
    for sh in data["shapes"]:
        if sh["id"] in sacrificial:
            continue
        m_name = sh.get("material") or sh["id"]
        m = table[m_name]
        kw = [f"E={_fmt(m['E'])}", f"nu={_fmt(m['nu'])}"]
        for k in ("G", "fy", "density"):
            if m.get(k) is not None:
                kw.append(f"{k}={_fmt(m[k])}")
        out.append(
            f"    {_fmt(sh['id'])}: SectionMaterial({', '.join(kw)}),"
        )
    return out


# ── fiber lane ───────────────────────────────────────────────────────

_RECT_KEYS = ("ny", "nz", "yI", "zI", "yJ", "zJ")
_CIRC_KEYS = (
    "n_circ", "n_rad", "yC", "zC", "int_rad", "ext_rad",
    "start_ang", "end_ang",
)
_LAYER_KEYS = ("n_bars", "area", "yI", "zI", "yJ", "zJ")
_POINT_KEYS = ("y", "z", "area")


def _render_fiber(doc: Any) -> str:
    data = doc.to_dict()
    name = data.get("name") or "section"
    recipe = doc.build()
    used = sorted({
        i["material"]
        for i in (*recipe.patches, *recipe.layers, *recipe.points)
    })
    table = data["materials"]
    out: list[str] = [
        f'"""Generated by apeGmsh SectionDocument {name!r} '
        f'(section_doc_version {data["section_doc_version"]}).\n'
        f'One-way export; templates are expanded to literals below '
        f'(provenance in comments)."""',
        "from apeGmsh.opensees.section.fiber import (",
        "    CircPatch, FiberPoint, RectPatch, StraightLayer,",
        ")",
        "",
        "",
        "def build_section(ops, *, name=None):",
        f'    """Construct the {name!r} fiber section on an apeSees '
        f'bridge."""',
    ]
    for m in used:
        spec = table[m].get("uniaxial")
        if not spec:
            raise ValueError(
                f"export_script: material {m!r} has no uniaxial spec."
            )
        kw = ", ".join(
            f"{k}={_fmt(v)}" for k, v in spec["params"].items()
        )
        out.append(
            f"    m_{_ident(m)} = ops.uniaxialMaterial."
            f"{spec['type']}({kw})"
        )
    out.append("")
    for t in data["templates"]:
        params = ", ".join(
            f"{k}={_fmt(v)}" for k, v in t["params"].items()
        )
        out.append(
            f"    # expanded from template {t['template']}({params}) "
            f"with roles {t['materials']}"
        )
    out.append("    patches = (")
    for p in recipe.patches:
        mat = f"m_{_ident(p['material'])}"
        if p["kind"] == "rect":
            out.append(
                f"        RectPatch(material={mat}, "
                f"{_kwargs(p, _RECT_KEYS)}),"
            )
        else:
            args = {k: p.get(k, 0.0) for k in _CIRC_KEYS}
            args["start_ang"] = p.get("start_ang", 0.0)
            args["end_ang"] = p.get("end_ang", 360.0)
            out.append(
                f"        CircPatch(material={mat}, "
                f"{_kwargs(args, _CIRC_KEYS)}),"
            )
    out.append("    )")
    out.append("    layers = (")
    for la in recipe.layers:
        out.append(
            f"        StraightLayer(material=m_{_ident(la['material'])}, "
            f"{_kwargs(la, _LAYER_KEYS)}),"
        )
    out.append("    )")
    out.append("    points = (")
    for pt in recipe.points:
        out.append(
            f"        FiberPoint(material=m_{_ident(pt['material'])}, "
            f"{_kwargs(pt, _POINT_KEYS)}),"
        )
    out.append("    )")
    gj = "None" if recipe.GJ is None else _fmt(recipe.GJ)
    out += [
        "    return ops.section.Fiber(",
        "        patches=patches, layers=layers, fibers=points,",
        f"        GJ={gj}, name=name,",
        "    )",
        "",
    ]
    return "\n".join(out)
