"""Deck provenance stamps (F2-d, #1511): the emitter-side header.

The oracle is a closed form, the slice card's header contract:

* ``backend=None`` (the default) leaves both headers byte-identical to
  before the slice: the banner alone on Tcl; banner, import, wipe on py;
* a fork :class:`BackendInfo` adds one line after the banner carrying the
  apeGmsh version, ``kind`` and ``build``;
* a stock one carries ``kind`` and no ``build``;
* the golden mask replaces the version and the build with tokens and
  touches nothing else.

Fork-free: every backend here is a fake ``BackendInfo``, never the real
(maybe stale) build.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from apeGmsh import __version__
from apeGmsh.opensees._target import BackendInfo
from apeGmsh.opensees.emitter.py import PyEmitter
from apeGmsh.opensees.emitter.tcl import (
    DECK_BANNER,
    TclEmitter,
    provenance_stamp,
)

from tests.opensees.golden import builder

_SHA = "a240b9183c0ffee0123456789abcdef012345678"
_FORK = BackendInfo(kind="fork", build=_SHA, version="3.8.0", source="x")
_STOCK = BackendInfo(kind="stock", build=None, version="3.7.1", source="y")

# The headers as they were before F2-d, verbatim.
_TCL_HEADER_BEFORE = ["# auto-generated by apeGmsh.opensees; do not edit by hand"]
_PY_HEADER_BEFORE = [
    "# auto-generated by apeGmsh.opensees; do not edit by hand",
    "import openseespy.opensees as ops",
    "ops.wipe()",
]


# --------------------------------------------------------------------------
# None keeps today's header
# --------------------------------------------------------------------------
def test_tcl_header_without_backend_is_unchanged() -> None:
    assert TclEmitter().lines() == _TCL_HEADER_BEFORE
    assert TclEmitter(backend=None).lines() == _TCL_HEADER_BEFORE


def test_py_header_without_backend_is_unchanged() -> None:
    assert PyEmitter().lines() == _PY_HEADER_BEFORE
    assert PyEmitter(backend=None).lines() == _PY_HEADER_BEFORE


# --------------------------------------------------------------------------
# A backend stamps one line after the banner
# --------------------------------------------------------------------------
def test_fork_stamp_carries_version_kind_and_build() -> None:
    assert provenance_stamp(_FORK) == (
        f"# apeGmsh {__version__}; backend fork; build {_SHA}"
    )


def test_stock_stamp_carries_kind_and_no_build() -> None:
    stamp = provenance_stamp(_STOCK)
    assert stamp == f"# apeGmsh {__version__}; backend stock"
    assert "build" not in stamp


def test_tcl_header_with_fork_backend() -> None:
    assert TclEmitter(backend=_FORK).lines() == [
        DECK_BANNER,
        f"# apeGmsh {__version__}; backend fork; build {_SHA}",
    ]


def test_py_header_with_fork_backend_keeps_import_and_wipe_after() -> None:
    assert PyEmitter(backend=_FORK).lines() == [
        DECK_BANNER,
        f"# apeGmsh {__version__}; backend fork; build {_SHA}",
        "import openseespy.opensees as ops",
        "ops.wipe()",
    ]


def test_stamp_sits_after_banner_and_before_the_body() -> None:
    for em in (TclEmitter(backend=_STOCK), PyEmitter(backend=_STOCK)):
        em.model(ndm=3, ndf=6)
        lines = em.lines()
        assert lines[0] == DECK_BANNER
        assert lines[1] == f"# apeGmsh {__version__}; backend stock"
        assert "model" in lines[-1]


def test_preamble_still_leads_the_stamped_tcl_deck() -> None:
    em = TclEmitter(backend=_FORK)
    em.preamble("first")
    assert em.lines()[:3] == [
        "# first", DECK_BANNER, provenance_stamp(_FORK),
    ]


def test_stamp_flushes_to_a_stream_sink_before_the_body(
    tmp_path: Path,
) -> None:
    """Stream mode (ADR 0065 Tier 2) writes the header lines first."""
    em = TclEmitter(backend=_FORK)
    path = tmp_path / "deck.tcl"
    em.stream_to(str(path))
    em.model(ndm=3, ndf=3)
    em.stream_finish()
    lines = path.read_text(encoding="utf-8").splitlines()
    assert lines[:2] == [DECK_BANNER, provenance_stamp(_FORK)]
    assert lines[2].startswith("model BasicBuilder")


# --------------------------------------------------------------------------
# Fail closed at the seam
# --------------------------------------------------------------------------
@pytest.mark.parametrize("bad", ["fork", {"kind": "fork"}, object()])
def test_non_backend_info_is_refused(bad: object) -> None:
    with pytest.raises(TypeError, match="BackendInfo"):
        TclEmitter(backend=bad)  # type: ignore[arg-type]
    with pytest.raises(TypeError, match="BackendInfo"):
        PyEmitter(backend=bad)  # type: ignore[arg-type]


# --------------------------------------------------------------------------
# The golden mask
# --------------------------------------------------------------------------
def _masked(lines: list[str], tmp_path: Path) -> list[str]:
    return builder._normalise("\n".join(lines) + "\n", tmp_path).split("\n")


def test_mask_replaces_version_and_build_only(tmp_path: Path) -> None:
    got = _masked(TclEmitter(backend=_FORK).lines() + ["node 1 0.0"], tmp_path)
    assert got == [
        DECK_BANNER,
        "# apeGmsh <VERSION>; backend fork; build <BUILD>",
        "node 1 0.0",
        "",
    ]


def test_mask_on_stock_stamp_invents_no_build(tmp_path: Path) -> None:
    got = _masked(PyEmitter(backend=_STOCK).lines(), tmp_path)
    assert got[:2] == [DECK_BANNER, "# apeGmsh <VERSION>; backend stock"]
    assert got[2:] == ["import openseespy.opensees as ops", "ops.wipe()", ""]


def test_mask_leaves_an_unstamped_header_alone(tmp_path: Path) -> None:
    for before in (_TCL_HEADER_BEFORE, _PY_HEADER_BEFORE):
        assert _masked(before, tmp_path) == before + [""]


@pytest.mark.parametrize(
    "line",
    [
        "# apeGmsh 2.0.0; backend other",           # unknown kind
        "# apeGmsh 2.0.0; backend fork; build abc",  # not a full sha
        "## apeGmsh 2.0.0; backend fork",            # not the stamp line
        "puts {# apeGmsh 2.0.0; backend fork}",      # mid-line text
    ],
)
def test_mask_touches_only_a_well_formed_stamp_line(
    line: str, tmp_path: Path,
) -> None:
    assert _masked([line], tmp_path) == [line, ""]
