# auto-generated by apeGmsh.opensees; do not edit by hand
model BasicBuilder -ndm 3 -ndf 6
node 1 0.0 0.0 0.0
node 2 0.0 0.0 3.0
node 3 4.0 0.0 3.0
node 4 4.0 0.0 0.0
node 5 0.0 0.0 1.5
node 6 2.0 0.0 3.0
node 7 4.0 0.0 1.5
uniaxialMaterial Steel02 1 420000000 200000000000 0.01 20 0.925 0.15
section Fiber 1 -GJ 24000000 {
    fiber 0.1 0.0 0.005 1
    fiber -0.1 0.0 0.005 1
}
geomTransf Linear 1 0.0 1.0 0.0
beamIntegration Lobatto 1 1 3
timeSeries Linear 1
timeSeries Linear 2
element elasticBeamColumn 3 1 5 0.01 200000000000 80000000000 0.0003 0.0002 0.0001 1
element elasticBeamColumn 4 5 2 0.01 200000000000 80000000000 0.0003 0.0002 0.0001 1
element elasticBeamColumn 5 4 7 0.01 200000000000 80000000000 0.0003 0.0002 0.0001 1
element elasticBeamColumn 6 7 3 0.01 200000000000 80000000000 0.0003 0.0002 0.0001 1
element forceBeamColumn 7 2 6 1 1
element forceBeamColumn 8 6 3 1 1
fix 1 1 1 1 1 1 1
fix 4 1 1 1 1 1 1
mass 2 100.0 100.0 100.0 0.0 0.0 0.0
pattern Plain 1 1 {
    load 2 5000.0 0.0 0.0 0.0 0.0 0.0
}
pattern Plain 2 2 {
    load 2 10000.0 0.0 0.0 0.0 0.0 0.0
}
