# auto-generated by apeGmsh.opensees; do not edit by hand
model BasicBuilder -ndm 3 -ndf 6
uniaxialMaterial ASDConcrete1D 1 30000.0 -Te 0.0 9e-05 0.00015 0.0001597663211186248 0.0004989316055931241 0.004989316055931241 -Ts 0.0 2.7 3.0 0.6000000000000001 0.003 0.003 -Td 0.0 0.0 0.0 0.0 0.9989978586355426 0.9999782143181639 -Ce 0.0 0.0005 0.0006666666666666666 0.0008333333333333333 0.001 0.0011666666666666665 0.0013333333333333333 0.0015 0.0016666666666666666 0.0018333333333333333 0.002 0.004718775313404538 0.005218775313404539 -Cs 0.0 15.0 19.282032302755088 22.459666924148337 24.852813742385703 26.6515138991168 27.979589711327122 28.92304845413264 29.54451150103322 29.891252930760572 30.0 3.0 3.0 -Cd 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.8805347783408092 0.9252092474800667 -implex -autoRegularization 500.0
uniaxialMaterial Elastic 2 30000.0
timeSeries Linear 1
section Fiber 1 -GJ 1000000000000.0 {
    fiber -150.0 -150.0 22500.0 1
    fiber -150.0 150.0 22500.0 1
    fiber 150.0 -150.0 22500.0 1
    fiber 150.0 150.0 22500.0 1
}
section Fiber 2 -GJ 1000000000000.0 {
    fiber -150.0 -150.0 22500.0 2
    fiber -150.0 150.0 22500.0 2
    fiber 150.0 -150.0 22500.0 2
    fiber 150.0 150.0 22500.0 2
}
beamIntegration Lobatto 1 1 3
beamIntegration Lobatto 2 2 3
geomTransf Linear 1 1.0 0.0 0.0
if {[info commands getPID] == ""} { proc getPID {} { return 0 } }
if {[getPID] == 0} {
    node 1 0.0 0.0 0.0
    node 2 0.0 0.0 1500.0
    node 3 0.0 0.0 3000.0
    node 4 1000.0 0.0 0.0
    node 5 1000.0 0.0 1500.0
    node 6 1000.0 0.0 3000.0
    node 7 2000.0 0.0 0.0
    node 8 2000.0 0.0 1500.0
    node 9 2000.0 0.0 3000.0
    element forceBeamColumn 1 1 2 1 1
    element forceBeamColumn 2 2 3 1 1
    element forceBeamColumn 3 4 5 1 1
    element forceBeamColumn 4 5 6 1 1
    element forceBeamColumn 5 7 8 1 2
    element forceBeamColumn 6 8 9 1 2
    fix 1 1 1 1 1 1 1
    fix 4 1 1 1 1 1 1
    fix 7 1 1 1 1 1 1
    mass 3 1.0 1.0 1.0 0.0 0.0 0.0
    mass 6 1.0 1.0 1.0 0.0 0.0 0.0
    mass 9 1.0 1.0 1.0 0.0 0.0 0.0
}

if {[getPID] == 1} {
    node 10 3000.0 0.0 0.0
    node 11 3000.0 0.0 1500.0
    node 12 3000.0 0.0 3000.0
    node 13 4000.0 0.0 0.0
    node 14 4000.0 0.0 1500.0
    node 15 4000.0 0.0 3000.0
    node 16 5000.0 0.0 0.0
    node 17 5000.0 0.0 1500.0
    node 18 5000.0 0.0 3000.0
    element forceBeamColumn 7 10 11 1 1
    element forceBeamColumn 8 11 12 1 1
    element forceBeamColumn 9 13 14 1 1
    element forceBeamColumn 10 14 15 1 1
    element forceBeamColumn 11 16 17 1 2
    element forceBeamColumn 12 17 18 1 2
    fix 10 1 1 1 1 1 1
    fix 13 1 1 1 1 1 1
    fix 16 1 1 1 1 1 1
    mass 12 1.0 1.0 1.0 0.0 0.0 0.0
    mass 15 1.0 1.0 1.0 0.0 0.0 0.0
    mass 18 1.0 1.0 1.0 0.0 0.0 0.0
}

# apeSees IMPL-EX time driver (ADR 0113): persistent dTime / dTimeCommit / dTimeInitial parameters
parameter 1
parameter 2
parameter 3
proc _apesees_implex_dt {dt first} {
    if {$first} {
        updateParameter 2 $dt
        updateParameter 3 $dt
    }
    updateParameter 1 $dt
}
if {[getPID] == 0} {
    foreach _apesees_e [list \
        1 2 3 4] {
        addToParameter 1 element $_apesees_e dTime
        addToParameter 2 element $_apesees_e dTimeCommit
        addToParameter 3 element $_apesees_e dTimeInitial
    }
}

if {[getPID] == 1} {
    foreach _apesees_e [list \
        7 8 9 10] {
        addToParameter 1 element $_apesees_e dTime
        addToParameter 2 element $_apesees_e dTimeCommit
        addToParameter 3 element $_apesees_e dTimeInitial
    }
}

# === Stage: gravity ===
domainChange
constraints Plain
numberer ParallelPlain
system Mumps -matrixType 0
test NormDispIncr 1e-08 50 0 2
algorithm Newton
integrator LoadControl 0.1
analysis Static
if {[getPID] == 0} {
    pattern Plain 1 1 {
        load 3 0.0 0.0 -1000000.0 0.0 0.0 0.0
        load 6 0.0 0.0 -1000000.0 0.0 0.0 0.0
        load 9 0.0 0.0 -1000000.0 0.0 0.0 0.0
    }
}

if {[getPID] == 1} {
    pattern Plain 1 1 {
        load 12 0.0 0.0 -1000000.0 0.0 0.0 0.0
        load 15 0.0 0.0 -1000000.0 0.0 0.0 0.0
        load 18 0.0 0.0 -1000000.0 0.0 0.0 0.0
    }
}

_apesees_implex_dt 0.1 1
for {set _apesees_i 0} {$_apesees_i < 10} {incr _apesees_i} {
    if {[analyze 1] != 0} {
        error "apeGmsh: analyze FAILED at increment [expr {$_apesees_i + 1}]/10 of stage 'gravity' (pseudo-time [getTime]) -- aborting, the remaining deck would run on a partial state"
    }
}
# ---- ADR 0113 smoke probe (not bridge output): stage gravity
foreach _p_e [getEleTags] {
    if {[lsearch -exact {1 2 3 4 7 8 9 10} $_p_e] >= 0} {
        puts "IMPLEX_PROBE stage=gravity rank=[getPID] ele=$_p_e [eleResponse $_p_e section 1 fiber 0 time]"
    }
}
loadConst -time 0.0
wipeAnalysis
# === Stage: hold ===
domainChange
constraints Plain
numberer ParallelPlain
system Mumps -matrixType 0
test NormDispIncr 1e-08 50 0 2
algorithm Newton
integrator LoadControl 0.02
analysis Static
_apesees_implex_dt 0.02 1
for {set _apesees_i 0} {$_apesees_i < 5} {incr _apesees_i} {
    if {[analyze 1] != 0} {
        error "apeGmsh: analyze FAILED at increment [expr {$_apesees_i + 1}]/5 of stage 'hold' (pseudo-time [getTime]) -- aborting, the remaining deck would run on a partial state"
    }
}
# ---- ADR 0113 smoke probe (not bridge output): stage hold
foreach _p_e [getEleTags] {
    if {[lsearch -exact {1 2 3 4 7 8 9 10} $_p_e] >= 0} {
        puts "IMPLEX_PROBE stage=hold rank=[getPID] ele=$_p_e [eleResponse $_p_e section 1 fiber 0 time]"
    }
}
loadConst -time 0.0
wipeAnalysis
# === Stage: transient ===
domainChange
constraints Plain
numberer ParallelPlain
system Mumps -matrixType 0
test NormDispIncr 1e-08 50 0 2
algorithm Newton
integrator Newmark 0.5 0.25
analysis Transient
_apesees_implex_dt 0.01 1
for {set _apesees_i 0} {$_apesees_i < 5} {incr _apesees_i} {
    if {[analyze 1 0.01] != 0} {
        error "apeGmsh: analyze FAILED at increment [expr {$_apesees_i + 1}]/5 of stage 'transient' (pseudo-time [getTime]) -- aborting, the remaining deck would run on a partial state"
    }
}
# ---- ADR 0113 smoke probe (not bridge output): stage transient
foreach _p_e [getEleTags] {
    if {[lsearch -exact {1 2 3 4 7 8 9 10} $_p_e] >= 0} {
        puts "IMPLEX_PROBE stage=transient rank=[getPID] ele=$_p_e [eleResponse $_p_e section 1 fiber 0 time]"
    }
}
loadConst -time 0.0
wipeAnalysis
