# auto-generated by apeGmsh.opensees; do not edit by hand
model BasicBuilder -ndm 3 -ndf 3
nDMaterial ElasticIsotropic 1 1000000.0 0.3 0.0
uniaxialMaterial Elastic 1 200000000000.0
if {[info commands getPID] == ""} { proc getPID {} { return 0 } }
if {[getPID] == 0} {
    node 2 0.0 0.0 1.0
    node 7 1.0 0.0 0.0
    node 18 1.0 1.0 1.0
    node 55 0.0 1.0 0.0
    node 73 0.0 1.0 1.0
    node 104 0.0 0.0 0.0
    node 300 1.0 0.0 1.0
    node 9001 1.0 1.0 0.0
    element stdBrick 4 104 7 9001 55 2 300 18 73 1
    fix 104 1 1 1
    fix 7 1 1 1
    fix 9001 1 1 1
    fix 55 1 1 1
}

if {[getPID] == 1} {
    node 2 0.0 0.0 1.0
    node 9 1.0 0.0 2.0
    node 18 1.0 1.0 1.0
    node 64 1.0 1.0 2.0
    node 73 0.0 1.0 1.0
    node 210 0.0 0.0 2.0
    node 300 1.0 0.0 1.0
    node 5000 0.0 1.0 2.0
    element stdBrick 5 2 300 18 73 210 9 64 5000 1
}

if {[getPID] == 2} {
    node 9 1.0 0.0 2.0
    node 31 0.0 0.0 3.0
    node 88 1.0 0.0 3.0
    node 210 0.0 0.0 2.0
    element Truss 6 210 31 0.0001 1
    element Truss 7 9 88 0.0001 1
    element Truss 8 31 88 0.0001 1
}

# === Stage: base_state ===
domainChange
constraints Plain
numberer RCM
system UmfPack
test NormDispIncr 0.0001 50 0 2
algorithm Newton
integrator LoadControl 0.1
analysis Static
for {set _apesees_i 0} {$_apesees_i < 2} {incr _apesees_i} {
    if {[analyze 1] != 0} {
        error "apeGmsh: analyze FAILED at increment [expr {$_apesees_i + 1}]/2 of stage 'base_state' (pseudo-time [getTime]) -- aborting, the remaining deck would run on a partial state"
    }
    if {[expr {($_apesees_i + 1) % 1}] == 0 || [expr {$_apesees_i + 1}] == 2} {
        puts "APEGMSH_PROGRESS i=[expr {$_apesees_i + 1}] n=2 t=[getTime]"
        flush stdout
    }
}
loadConst -time 0.0
wipeAnalysis
# === Stage: swap_bars ===
if {[getPID] == 1} {
    node 11 2.0 1.0 2.0
    node 402 2.0 0.0 2.0
    element Truss 9 9 402 0.0001 1
    element Truss 10 5000 11 0.0001 1
}

if {[getPID] == 2} {
remove element 8
}

domainChange
constraints Plain
numberer RCM
system UmfPack
test NormDispIncr 0.0001 50 0 2
algorithm Newton
integrator LoadControl 0.1
analysis Static
for {set _apesees_i 0} {$_apesees_i < 2} {incr _apesees_i} {
    if {[analyze 1] != 0} {
        error "apeGmsh: analyze FAILED at increment [expr {$_apesees_i + 1}]/2 of stage 'swap_bars' (pseudo-time [getTime]) -- aborting, the remaining deck would run on a partial state"
    }
    if {[expr {($_apesees_i + 1) % 1}] == 0 || [expr {$_apesees_i + 1}] == 2} {
        puts "APEGMSH_PROGRESS i=[expr {$_apesees_i + 1}] n=2 t=[getTime]"
        flush stdout
    }
}
loadConst -time 0.0
wipeAnalysis
