"""Generate the ADR index (decisions/README.md) from the ADR files.

The README is the hand-written preamble, kept verbatim above ``MARKER``,
followed by one short row per ADR: ``| [NNNN](file) | title | status |``.
The title is the H1 (minus its ``# ADR NNNN —`` prefix) and the status is the
first clause of the ``**Status:**`` line, so the ADR file is the single source.

    python scripts/adr_index.py           # rewrite the README
    python scripts/adr_index.py --check   # exit 1 when the README is stale

Stdlib only. `scripts/check_quirks.py` runs the check as part of `adr-number`.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DECISIONS = Path("src/apeGmsh/opensees/architecture/decisions")
MARKER = "<!-- generated by scripts/adr_index.py: do not edit below; run `python scripts/adr_index.py` -->"
LEGACY_HEADER = "| # | Title | Status |"

_TITLE = re.compile(r"^#\s*ADR\s+\d{4}\s*[—–-]+\s*(?P<t>.+?)\s*$")
_WORD = re.compile(
    r"(?P<w>superseded by \d{4}|accepted|proposed|superseded|rejected|deprecated|draft)\b",
    re.IGNORECASE,
)


def parse_adr(path: Path) -> tuple[str, str]:
    """Return (title, short status) for one ADR file, or raise ValueError."""
    lines = path.read_text(encoding="utf-8").splitlines()
    match = _TITLE.match(lines[0]) if lines else None
    if match is None:
        raise ValueError(f"{path.name}: first line is not '# ADR NNNN — <title>'")
    statuses = [ln for ln in lines[:30] if ln.startswith("**Status:**")]
    if len(statuses) != 1:
        raise ValueError(
            f"{path.name}: expected one '**Status:**' line in the header, found {len(statuses)}"
        )
    text = statuses[0][len("**Status:**"):].strip().lstrip("*").strip()
    word = _WORD.match(text)
    if word:
        first = word.group("w")
        status = first[:1].upper() + first[1:].lower()
    else:
        status = re.split(r" \(|[.;,]| —| --", text)[0].strip()
    return match.group("t").replace("|", "\\|"), status


def generate(root: Path) -> str:
    folder = root / DECISIONS
    text = (folder / "README.md").read_text(encoding="utf-8")
    cut = text.index(MARKER) if MARKER in text else text.index(LEGACY_HEADER)
    rows = [LEGACY_HEADER, "|---|---|---|"]
    for path in sorted(folder.glob("[0-9][0-9][0-9][0-9]-*.md")):
        title, status = parse_adr(path)
        rows.append(f"| [{path.name[:4]}]({path.name}) | {title} | {status} |")
    return text[:cut].rstrip("\n") + "\n\n" + MARKER + "\n\n" + "\n".join(rows) + "\n"


def is_stale(root: Path) -> bool:
    return (root / DECISIONS / "README.md").read_text(encoding="utf-8") != generate(root)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--root", type=Path, default=REPO)
    parser.add_argument("--check", action="store_true", help="exit 1 if the README is stale")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.check:
        if is_stale(root):
            print("decisions/README.md is stale: run `python scripts/adr_index.py`")
            return 1
        return 0
    (root / DECISIONS / "README.md").write_text(generate(root), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
