# auto-generated by apeGmsh.opensees; do not edit by hand
model BasicBuilder -ndm 3 -ndf 3
nDMaterial ElasticIsotropic 1 20000000.0 0.0 0.0
timeSeries Linear 1
constraints LadrunoContact
numberer ParallelPlain
system Mumps
test NormDispIncr 1e-10 50 0 2
algorithm Newton
integrator LoadControl 1.0
constraints LadrunoContact
analysis Static
if {[info commands getPID] == ""} { proc getPID {} { return 0 } }
if {[getPID] == 0} {
    node 1 0.0 0.0 1.0
    node 2 0.0 0.0 0.0
    node 3 0.0 1.0 1.0
    node 4 0.0 1.0 0.0
    node 5 1.0 0.0 1.0
    node 6 1.0 0.0 0.0
    node 7 1.0 1.0 1.0
    node 8 1.0 1.0 0.0
    element stdBrick 2 3 1 2 4 7 5 6 8 1
    fix 2 1 1 1
    fix 4 1 1 1
    fix 6 1 1 1
    fix 8 1 1 1
    fix 1 1 1 0
    fix 3 1 1 0
    fix 5 1 1 0
    fix 7 1 1 0
    node 10 0.0 0.0 0.999
    fix 10 1 1 0
    node 12 0.0 1.0 0.999
    fix 12 1 1 0
    node 14 1.0 0.0 0.999
    fix 14 1 1 0
    node 16 1.0 1.0 0.999
    fix 16 1 1 0
    # s5twin
    contactSurface 1 -master 4 1 5 7 3
    contactSurface 2 -slave 10 12 14 16
    contact 1 1 2 auto -outward 0.0 0.0 1.0
}

if {[getPID] == 1} {
    node 9 0.0 0.0 1.999
    node 10 0.0 0.0 0.999
    node 11 0.0 1.0 1.999
    node 12 0.0 1.0 0.999
    node 13 1.0 0.0 1.999
    node 14 1.0 0.0 0.999
    node 15 1.0 1.0 1.999
    node 16 1.0 1.0 0.999
    element stdBrick 3 11 9 10 12 15 13 14 16 1
    fix 10 1 1 0
    fix 12 1 1 0
    fix 14 1 1 0
    fix 16 1 1 0
    fix 9 1 1 0
    fix 11 1 1 0
    fix 13 1 1 0
    fix 15 1 1 0
    pattern Plain 1 1 {
        load 9 0.0 0.0 -2500.0
        load 11 0.0 0.0 -2500.0
        load 13 0.0 0.0 -2500.0
        load 15 0.0 0.0 -2500.0
    }
}

recorder ladruno s6_mp.ladruno -N displacement -E stresses

set ok [analyze 1]
puts [format "S6 ok=%d" $ok]
wipe
